# -*- coding: utf-8 -*-
"""TomographyInversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bdUY_CicG4WcJx35cjHJw9q5KsxYrPhe
"""

import numpy as np
import matplotlib.pyplot as plt

# Energy array (values of the left bin borders)
x_array = np.logspace(np.log10(1.), np.log10(37.15513054), num=50)

# cos(theta) array (values of the left bin borders)
y_array = np.cos(np.linspace(np.arccos(-1.0), np.arccos(-0.03141076), num=50))

# these arrays are the ones given by EarthProbe

rho_core   = 11.8504
rho_mantle = 4.6679

eps_c = rho_core*0.01
eps_m = rho_mantle*0.01

#Files needed

#1) Interacting Events for +1% variation in the core (ne_c + eps_c) (needed for dg(m)/dm1)
int_anue_C1  = np.loadtxt("Data/h_int_anue_cc_0.010_core.txt")
int_nue_C1   = np.loadtxt("Data/h_int_nue_cc_0.010_core.txt")
int_anumu_C1 = np.loadtxt("Data/h_int_anumu_cc_0.010_core.txt")
int_numu_C1  = np.loadtxt("Data/h_int_numu_cc_0.010_core.txt")

#2) Interacting Events for +1% variation in the mantle (ne_m + eps_m) (needed for dg(m)/dm2)
int_anue_M1  = np.loadtxt("Data/h_int_anue_cc_0.010_mantle.txt")
int_nue_M1   = np.loadtxt("Data/h_int_nue_cc_0.010_mantle.txt")
int_anumu_M1 = np.loadtxt("Data/h_int_anumu_cc_0.010_mantle.txt")
int_numu_M1  = np.loadtxt("Data/h_int_numu_cc_0.010_mantle.txt")

#3) PREM interacting events (needed for g(m), dg(m)/dm1 and dg(m)/dm2)
int_anue_PREM  = np.loadtxt("Data/h_int_anue_cc_PREM.txt")
int_nue_PREM   = np.loadtxt("Data/h_int_nue_cc_PREM.txt")
int_anumu_PREM = np.loadtxt("Data/h_int_anumu_cc_PREM.txt")
int_numu_PREM  = np.loadtxt("Data/h_int_numu_cc_PREM.txt")

#4) Observed Interacting events (dobs)
# for now we reuse data from above

# dobs is the "true" observation
# In a future, this will be the actual measurement
# For now, we can test different scenarios
# e.g. what if the core was a bit denser?:

dobs = {"elec": int_anue_C1  + int_nue_C1,
        "muon": int_anumu_C1 + int_numu_C1}

# g evaluated in m_0, with m_0 = PREM
g_m0 = {"elec": int_anue_PREM  + int_nue_PREM,
        "muon": int_anumu_PREM + int_numu_PREM}

# For Parial derivatives
gpremmod_m1 = {"elec": int_anue_C1  + int_nue_C1,
               "muon": int_anumu_C1 + int_numu_C1}

gpremmod_m2 = {"elec": int_anue_M1  + int_nue_M1,
               "muon": int_anumu_M1 + int_numu_M1}

classes  = {"elec","muon"}
NEBins   = len(x_array)
NCosBins = len(y_array)

def DeltaF():

   ## Compute Δm1 and Δm2 that minimize the misfit function F.
   ## Solves a 2x2 non-homogeneous linear system using derivatives of
   ## the model output.

    # Initialize derivatives and coefficients
    dg_dm1 = {"elec": (gpremmod_m1["elec"] - g_m0["elec"])/eps_c,
              "muon": (gpremmod_m1["muon"] - g_m0["muon"])/eps_c}
    dg_dm2 = {"elec": (gpremmod_m2["elec"] - g_m0["elec"])/eps_m,
              "muon": (gpremmod_m2["muon"] - g_m0["muon"])/eps_m}

    C_1 = 0
    C_2 = 0

    A11 = 0
    A12 = 0
    A21 = 0
    A22 = 0

    # Loop over data bins
    for clss in classes:
        for j in range(NEBins):
            for i in range(NCosBins):

                # Example access pattern (update dg_dm1, dg_dm2 if needed)
                residual = (g_m0[clss] - dobs[clss])[i, j]

                C_1 += residual * dg_dm1[clss][i, j]
                C_2 += residual * dg_dm2[clss][i, j]

                A11 += dg_dm1[clss][i, j] * dg_dm1[clss][i, j]
                A12 += dg_dm1[clss][i, j] * dg_dm2[clss][i, j]
                A21 += dg_dm1[clss][i, j] * dg_dm2[clss][i, j]
                A22 += dg_dm2[clss][i, j] * dg_dm2[clss][i, j]

    # Coefficient matrix
    A = np.array([[A11, A12],
                  [A21, A22]])

    # Right-hand side (non-homogeneous term)
    b = np.array([C_1, C_2])

    # Solve the 2x2 system: A * x = b
    x = np.linalg.solve(A, b)

    # Return Δm1 and Δm2
    return x[0], x[1]

